# Generated by Django 4.2.16 on 2024-09-26 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("high_level", "0002_etape_machine_ressource_usine_stock_siegesocial_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="etape",
            name="machine",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="high_level.machine",
            ),
        ),
        migrations.AlterField(
            model_name="etape",
            name="quantite_ressource",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="high_level.quantiteressource",
            ),
        ),
        migrations.AlterField(
            model_name="produit",
            name="premiere_etape",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="high_level.etape",
            ),
        ),
        migrations.AlterField(
            model_name="quantiteressource",
            name="ressource",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="high_level.ressource",
            ),
        ),
        migrations.AlterField(
            model_name="siegesocial",
            name="ville",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="high_level.ville",
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="ressource",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="high_level.ressource",
            ),
        ),
        migrations.AlterField(
            model_name="usine",
            name="ville",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="high_level.ville",
            ),
        ),
    ]
