# Generated by Django 4.2.16 on 2024-09-27 09:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("high_level", "0004_stock_usine"),
    ]

    operations = [
        migrations.RenameField(
            model_name="siegesocial",
            old_name="president",
            new_name="CEO",
        ),
    ]
